/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phoenix_jnidemo_HelloJni */

#ifndef _Included_com_phoenix_jnidemo_HelloJni
#define _Included_com_phoenix_jnidemo_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phoenix_jnidemo_HelloJni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_phoenix_jnidemo_HelloJni_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
